### ISSUE TITLE
Use <var> tag instead of <i> tag

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#12]
For math variables outside of a MathML context. This occur throughout:
- Chapter 4 line 114, 115, 122, 136, 138, 139, 140, 142, 144, 146, 154, 159, 162, 164, 167, 169, 221
- Chapter 6 line 57, 58

**Comment by gsegol** [comment]
If italics are not sufficient, please explain what you want.
Thanks

Geneviėve
***@***.***

**Comment by thewchan** [comment]
Yes sorry for the confusion, I had put part of my recommendation in the subject line. Please wrap all algebraic variables in `<var>` tags instead of `<i>` tags, as per Robin and Alex.

**Comment by gsegol** [comment]
Done

**Comment by gsegol** [comment]
Done
