### ISSUE TITLE
Double check se-lint-ignore

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#13]
Once you have changed A.M. and P.M. to a.m. and p.m., the linter should stop complaining and you won't need the rules. (s-023) Make sure you are on the newest version of the toolset (2.2.0).

**Comment by gsegol** [comment]
Emma told me they should be capitalized.  But never mind.
Geneviėve
***@***.***

**Comment by thewchan** [comment]
Yeah check with Alex just to be sure... This is an edge case that should be written down somewhere, I think

**Comment by gsegol** [comment]
I left only one s-23 to ignore, but not yet out of the woods with am and pm.
