### ISSUE TITLE
Mordernize spellings

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#2]
Modernize spellings returned one you might want update:
Chapter-19, line 58 any body -> anybody

**Comment by gsegol** [comment]
Actually, in this case, “body” refers to the projectile or to a celestial “body,” not to a person.  So, it is any body not anybody.

Geneviėve
***@***.***

**Comment by thewchan** [comment]
Gotcha 👍
