### ISSUE TITLE
Missing <abbr> tags

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#3]
Chapter 21, line 37, need `<abbr>` tags around "a.m."
Chapter 6, line 89, need `<abbr> tags around "etc."; this one needs a `class="eoc"` attribute as well (per https://standardebooks.org/manual/1.6.2/single-page#8.10.3)

**Comment by thewchan** [comment]
Also in chapter 12, around `lat.` and `long.` (e.g. line 196)

**Comment by thewchan** [comment]
Chapter 17, around `lat.` and `long.` line 48

**Comment by thewchan** [comment]
Chatper 5 line 95:
`<abbr epub:type="z3998:given-name">M.</abbr> Pouillet,`

If `M.` is short for Monsieur, then no given-name semantics should be added, however, if it is an initial, then the semantics should be kept. Need to double check here.

**Comment by gsegol** [comment]
M. is a given name.
<abbr> added where indicated

**Comment by gsegol** [comment]
Done
