### ISSUE TITLE
diverse -> divers

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#6]
There's a false positive from modernize spelling that slipped through in chapter 22, line 40, `diverse` should be `divers`

**Comment by gsegol** [comment]
I have corrected that numerous times.  Did you rerun typogrify or clean?  that brings it back again.  Drives me crazy.
Geneviėve
***@***.***

**Comment by thewchan** [comment]
I think it's the modernize-spelling that might be the culprit; just the interactive replace tool from SE to help catch these

**Comment by gsegol** [comment]
Done
