### ISSUE TITLE
Missing xml:lang attribute

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#7]
Missing a French language attribute for `Parbleu` in chapter-3 line 32

**Comment by thewchan** [comment]
Possibly `blafard` in chapter 15 line 66 need a French language attribute for the `<i> tag

**Comment by thewchan** [comment]
nimbo in chapter 17 line 43, I think this is a Spanish word, meaning "halo"

**Comment by thewchan** [comment]
chapter 3 line 45 `Nuits`, replace quotes with `<i>` with French (I think?) attributes

**Comment by gsegol** [comment]
Done.
